ph-ee-engine:
  zeebe-cluster:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

  zeebe-operate:
    enabled: false

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operations:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE tn03;
        CREATE DATABASE tn04;
        GRANT ALL PRIVILEGES ON tn03.* TO 'mifos';
        GRANT ALL PRIVILEGES ON tn04.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,bb"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "barebone-connector-channel.mifos.io"

  ph_ee_operations_app:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "barebone-operations.mifos.io"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "barebone-operations.mifos.io"
    webhost: "barebone-operations-ui.mifos.io"

  ph_ee_identity:
    hostname: "barebone-identity.mifos.io"
