ph-ee-engine:
  zeebe-cluster:
    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

  zeebe-operate:
    enabled: false

  elasticsearch:
    enabled: true
    replicas: 1
    clusterName: "ph-ee-elasticsearch"

  kibana:
    enabled: true
    elasticsearchHosts: "http://ph-ee-elasticsearch-master:9200/"

  operations:
    enabled: false

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,bb"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "barebone-dfsp-channels.mifos.io"

  ph_ee_identity_provider:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "barebone-identity.mifos.io"

  ph_ee_operations:
    hostname: "barebone-operations.mifos.io"
    webhost: "barebone-operations-ui.mifos.io"