ams:
  local:
    host: https://rhino.mifos.io:8443
    tenants:
      - name: tn03
        user: mifos
        password: password
        authtype: basic
        partyIdType: MSISDN
        partyId: 27710203999
      - name: tn04
        user: mifos
        password: password
        authtype: basic
        partyIdType: MSISDN
        partyId: 27710204999
