ams:
  local:
    host: https://leopard.mifos.io:8443
    tenants:
      - name: tn05
        user: mifos
        password: password
        authtype: basic
        partyIdType: MSISDN
        partyId: 27710305999
      - name: tn06
        user: mifos
        password: password
        authtype: basic
        partyIdType: MSISDN
        partyId: 27710306999
