camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

zeebe:
  broker:
    contactpoint: "127.0.0.1:26500"

ams:
  local:
    quote-enabled: false
