camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

zeebe:
  broker:
    contactpoint: "ph-ee-zeebe:26500"

ams:
  local:
    enabled: true
    version: cn
    keystore-path: keystore.jks
    keystore-password: openmf
    host: http://localhost:2027
    base-url: /interoperation/v1
    interop-quotes-path: ${ams.local.base-url}/quotes
    interop-parties-path: ${ams.local.base-url}/parties/{idType}/{idValue}
    interop-transfers-path: ${ams.local.base-url}/transfers
    auth:
      host: http://localhost:2021
      base-url: /identity/v1
      path: ${ams.local.auth.base-url}/token
