ams:
  local:
    interop:
      host: https://rhino.mifos.io:8443
    customer:
      host: https://rhino.mifos.io:8443
    account:
      host: https://rhino.mifos.io:8443
    auth:
      host: https://rhino.mifos.io:8443
    tenants:
      - name: "ibank-usa"
        user: mifos
        password: password
        authtype: basic
        fspId: in02tn03
      - name: "ibank-india"
        user: mifos
        password: password
        authtype: basic
        fspId: in02tn04
