ph-ee-engine-oaf:  
  zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe-cluster-helm:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
    image:
      repository: camunda/zeebe
      tag: 1.1.0

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

    extraInitContainers: |
      - name: init-ph-ee-kafka-exporter
        image: busybox:1.28
        command: ['/bin/sh', '-c']
        args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
        volumeMounts:
        - name: exporters
          mountPath: /exporters/

  zeebe-operate-helm:
    enabled: true
    image:
      repository: camunda/operate
      tag: 1.1.0
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
        clusterName: "ph-ee-elasticsearch"
    ingress:
      enabled: true
      className: "nginx"  
      path: /
      host: ph-zeebe.qa.oneacrefund.org
      tls:
        enabled: true
        secretName: oafqa-tls

  kibana:
    enabled: true
    imageTag: 7.13.2
    ingress:
      enabled: true
      className: "nginx"
      pathtype: ImplementationSpecific
      hosts:
        - host: ph-kibana.qa.oneacrefund.org
          paths:
            - path: /
      tls: 
        - secretName: oafqa-tls
          hosts:
            - "*.qa.oneacrefund.org"
    kibanaConfig:
      kibana.yml: |
        monitoring.enabled: false
        

  elasticsearch:
    enabled: true
    replicas: 1
    imageTag: 7.13.2
    minimumMasterNodes: 1

    #Single Node Solution
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s" 
    master:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30
    data:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30

  

    # Shrink default JVM heap.
    esJavaOpts: "-Xmx512m -Xms512m"

    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "200m"
        memory: "1024M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi

  operations:
    enabled: true

  operationsMysql:
    image:
      tag: "5.7"
      debug: true
    auth:
      database: "tenants"
      username: "mifos"
      password: "password"
      rootPassword: "4ET6ywqlGt"
    initdbScripts:
      setup.sql: |-
        CREATE DATABASE IF NOT EXISTS oaf;
        CREATE DATABASE IF NOT EXISTS messagegateway;
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';
        GRANT ALL PRIVILEGES ON oaf.* TO 'mifos';

  channel:
    DFSPIDS: "oaf"
    transaction_id_length: 20
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    AWS_ACCESS_KEY: "xxx"
    AWS_SECRET_KEY: "xxx"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-channel"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"

  operations_app:
    TENANTS: "oaf"
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-operations-app"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"

  operations_web:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ph-web.qa.oneacrefund.org"
    webhost: "ph-web.qa.oneacrefund.org"
    path: "/"
    image: "oaftech.azurecr.io/phee-ns/ops-web"
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"

  identity:
    hostname: "ops-bk.ibank.financial"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"

  mpesa:
    tenant: "oaf"
    enabled: true
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-mpesa"
    business_short_code: "668158"
    till_number: "9347335"
    callback_host: "https://paymenthub.qa.oneacrefund.org/mpesa"
    retry_count: 3
    safaricom:
      auth_host: "https://api.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://api.safaricom.co.ke"
    secret:
      value:
        client_key: "MHBMeGJOODNGck9sNU5kMEZoOVppNUJRbE14U0wybjUK"
        client_secret: "WXp1R05vSnhldWI4WkM2ZAo="
        pass_key: "YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOQo="
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"

  roster_connector:
    enabled: true
    SPRING_PROFILES_ACTIVE: "bb"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-ams-pesa"
    pesacore:
      auth_header: "PaymentHubTest"
    ams:
      local:
        enabled: true

  notifications:
    enabled: true
    SPRING_PROFILES_ACTIVE: "bb"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-notifications"
    hostname: "paymenthub.qa.oneacrefund.org"
    MESSAGEGATEWAYCONFIG_HOST: "paymenthub.qa.oneacrefund.org/messages"
    NOTIFICATION_LOCAL_HOST: "paymenthub.qa.oneacrefund.org/notifications"
    NOTIFICATION_SUCCESS_ENABLED: "false"
    NOTIFICATION_FAILURE_ENABLED: "true"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"


  zeebe_ops:
    enabled: true
    image: "oaftech.azurecr.io/phee-ns/phee-zeebe-ops"
    hostname: "paymenthub.qa.oneacrefund.org"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"

  messagegateway:
    enabled: true
    SECRET_NAME: "messagegateway-secret"
    image: "oaftech.azurecr.io/phee-ns/message-gateway"
    secret:
      name: "messagegateway-secret"
      key:
        telerivet_api_key: "api-key"
        telerivet_project_id: "project-id"
    hostname: "paymenthub.qa.oneacrefund.org"
    CALLBACKCONFIG_HOST: "paymenthub.qa.oneacrefund.org/notifications"
    HOSTCONFIG_HOST: "paymenthub.qa.oneacrefund.org/messages"
    MYSQL_USERNAME: "mifos"
    MYSQL_PASSWORD: "password"
    PROVIDERSOURCE_FROMDATABASE: "disabled"
    PROVIDERSOURCE_FROMYML: "enabled"
    ingress:
      annotations: 
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"


  importer_es:
    image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-es"

  importer_rdbms:
    image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-rdbms"
  
  wildcardhostname: "*.qa.oneacrefund.org"

  tls: "oafqa-tls"
