ph-ee-engine:
  zeebe-cluster:
    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"

    elasticsearch:
      enabled: false
    kibana:
      enabled: false

  zeebe-operate:
    enabled: false

  elasticsearch:
    enabled: true
    replicas: 1
    clusterName: "ph-ee-elasticsearch"

  kibana:
    enabled: true
    elasticsearchHosts: "http://ph-ee-elasticsearch-master:9200/"

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "operations"

  identityMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE tn05;
        CREATE DATABASE tn06;
        GRANT ALL PRIVILEGES ON tn05.* TO 'mifos';
        GRANT ALL PRIVILEGES ON tn06.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,med"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "med"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-dfsp-channels.mifos.io"

  ph_ee_identity_provider:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-identity.mifos.io"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-operations.mifos.io"
    webhost: "med-operations-ui.mifos.io"
