camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    party-lookup: "PayeePartyLookup-DFSPID"
    quote: "PayeeQuoteTransfer-DFSPID"

zeebe:
  broker:
    contactpoint: "ph-ee-zeebe:26500"

connector:
  ilp-secret: h4on38bsDjKiat2783gnklgafikmeuu5123kpobb7jm99

switch:
  host: http://40.114.81.46
  quote-service: quoting-service.local
  account-lookup-service: account-lookup-service.local
  transfer-service: ml-api-adapter.local

dfspids: "DFSPID"

parties:
  - partyIdType: MSISDN
    partyId: 27710101999
    dfspId: in01tn01
  - partyIdType: MSISDN
    partyId: 27710102999
    dfspId: in01tn02
  - partyIdType: MSISDN
    partyId: 27710203999
    dfspId: in02tn03
  - partyIdType: MSISDN
    partyId: 27710204999
    dfspId: in02tn04
  - partyIdType: MSISDN
    partyId: 27710305999
    dfspId: in03tn05
  - partyIdType: MSISDN
    partyId: 27710306999
    dfspId: in03tn06
