apiVersion: v2
name: ph-ee-superset-release
description: PaymentHub EE Barebone Edition

type: application
version: 0.2.0
appVersion: 1.16.0

dependencies:
- name: ph-ee-superset
  repository: https://fynarfin.io/images/
  version: 0.2.0