ph-ee-engine:
  zeebe-cluster:
    clusterSize: "3"
    partitionCount: "3"
    replicationFactor: "3"

    elasticsearch:
      enabled: true
    kibana:
      enabled: true

  zeebe-operate:
    enabled: true

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "operations"

  identityMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE tn01;
        CREATE DATABASE tn02;
        GRANT ALL PRIVILEGES ON tn01.* TO 'mifos';
        GRANT ALL PRIVILEGES ON tn02.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fincn,large"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "large"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-dfsp-channels.mifos.io"

  ph_ee_identity_provider:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-identity.mifos.io"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-operations.mifos.io"
    webhost: "large-operations-ui.mifos.io"
