camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "localhost:26500"

mpesa:
  auth:
    host: https://sandbox.safaricom.co.ke/oauth/v1/generate
    client-key: 0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5
    client-secret: YzuGNoJxeub8ZC6d
  api:
    lipana: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    transaction-status: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
    passKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919