camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

tenant: "oaf"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "localhost:26500"

operations:
  host: http://ph-ee-operations-app
  base-url: /api/v1/errorcode
  filter-path: /filter

mpesa:
  max-retry-count: 2
  api:
    lipana: /mpesa/stkpush/v1/processrequest
    transaction-status: /mpesa/stkpushquery/v1/query
  local:
    host: http://localhost:5000
    transaction-callback: /buygoods/callback
    queue-timeout-url: /queuetimeout/callback
    result-url: /result/callback

accounts:
  group:
    - name: "roster"
      business-short-code: ${ACCOUNTS.ROSTER.SHORTCODE:9383028}
      till: ${ACCOUNTS.ROSTER.TILL:1234567}
      auth-host:  ${ACCOUNTS.ROSTER.AUTHHOST:https://sandbox.safaricom.co.ke/oauth/v1/generate}
      client-key: ${ACCOUNTS.ROSTER.CLIENTKEY:0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5}
      client-secret:  ${ACCOUNTS.ROSTER.CLIENTSECRET:YzuGNoJxeub8ZC6d}
      api-host:  ${ACCOUNTS.ROSTER.APIHOST:https://sandbox.safaricom.co.ke}
      pass-key: ${ACCOUNTS.ROSTER.PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
    - name: "paygops"
      business-short-code: ${ACCOUNTS.PAYGOPS.SHORTCODE:7385028}
      till: ${ACCOUNTS.PAYGOPS.TILL:1234567}
      auth-host: ${ACCOUNTS.PAYGOPS.AUTHHOST:https://sandbox.safaricom.co.ke/oauth/v1/generate}
      client-key: ${ACCOUNTS.PAYGOPS.CLIENTKEY:0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5}
      client-secret: ${ACCOUNTS.PAYGOPS.CLIENTSECRET:YzuGNoJxeub8ZC6d}
      api-host: ${ACCOUNTS.PAYGOPS.APIHOST:https://sandbox.safaricom.co.ke}
      pass-key: ${ACCOUNTS.PAYGOPS.PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
    - name: "default"
      business-short-code: "7385028"
      till: "1234567"
      auth-host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      client-key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client-secret: "YzuGNoJxeub8ZC6d"
      api-host: "https://sandbox.safaricom.co.ke"
      pass-key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

logging:
  level:
    ROOT: INFO
