camel:
  server-port: ${PORT:5000}
  host: "" # Host URL for callback
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    some-flow: "SomeFlow-DFSPID"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 14
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "244c0260-712b-4378-93b4-70cc810b4888.zeebe.camunda.io:443"
    audience: "244c0260-712b-4378-93b4-70cc810b4888.zeebe.camunda.io"
    clientId: "eXKQYYuQwJe6M~Qa8ZVpW21DySzrue0I"
    clientSecret: "EtFosJAKuGIaX8PxJ.XkmH_x-3vOEIep_8Uu8FvGSCNDYgwfnH_U-kJBmfzzICPp"

gsma:
  auth:
    host: https://sandbox.mobilemoneyapi.io/v1/oauth/accesstoken
    client-key: bBvcGtIhyfAPNTMwuvACLyVrzcaTsyXR
    client-secret: PAL6ekftxxg02O58
  api:
    host: https://sandbox.mobilemoneyapi.io/oauth/simulator/v1.1/mm
    account: /accounts

dfspids: "DFSPID"
