camel:
  server-port: ${PORT:5000}
  host: "http://19724d3b3864.ngrok.io"
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    some-flow: "SomeFlow-DFSPID"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 14
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "4ae8d42c-5f02-4e18-b4d4-f4d3d92fc824.zeebe.camunda.io:443"
    audience: "4ae8d42c-5f02-4e18-b4d4-f4d3d92fc824.zeebe.camunda.io"
    clientId: "ruU.ptno_wct_PXW~ngW4Pp0A0QWw.E1"
    clientSecret: "is20pecUw4p_9s3DakWcayYPdDn.GhWfmkm7jtznSErP.ed1iR.z.Qg97EBVz~Pc"

gsma:
  auth:
    host: https://sandbox.mobilemoneyapi.io/v1/oauth/accesstoken
    client-key: bBvcGtIhyfAPNTMwuvACLyVrzcaTsyXR
    client-secret: PAL6ekftxxg02O58
  api:
    host: https://sandbox.mobilemoneyapi.io/oauth/simulator/v1.1/mm
    account: /accounts

dfspids: "DFSPID"
