apiVersion: v2
name: operations
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
- name: prometheus-community/prometheus
  version: 13.5.0

- name: grafana
  version: 6.5.0

