dependencies:
- name: kong
  version: 2.13.1
  repository: https://charts.konghq.com
  condition: "kong.enabled"
- name: keycloak
  version: 18.3.0
  repository: https://codecentric.github.io/helm-charts
  condition: "keycloak.enabled"