apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-rdbms
  labels:
    app: ph-ee-importer-rdbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-importer-rdbms
    spec:
      containers:
        - name: ph-ee-importer-rdbms
          image: paymenthubee.azurecr.io/phee/importer-rdbms

